language: java
jdk:
  - oraclejdk7
after_success:
  - ls -la ./target

language: python
python:
    - "2.7"

install:
    - "pip install -r requirements.txt"

script: nosetests

addons:
  hosts:
    - travis.example
