language:
    - java
    - python

addons:
  hosts:
    - travis.example

before_install:
    - sudo apt-get install -qq tree

install:
    - "pip install -r requirements.txt"

jdk:
  - oraclejdk7

python:
    - "2.7"

after_success:
  - tree

script: ./scripts/run-tests.sh

