language:
    - java
    - python

addons:
  hosts:
    - travis.example

before_install:
    - sudo apt-get install -qq tree
    - sudo apt-get install python-nose

after_install:
    - echo "after_install : " && tree

install:
    - "pip install -r requirements.txt"

jdk:
  - oraclejdk8
  - oraclejdk7

python:
    - "2.7"
    - "2.8"

env:
    - FOO=foo BAR=bar
    - FOO=bar BAR=foo

after_success:
  - tree

script: ./scripts/run-tests.sh

matrix:
    exclude:
        - jdk: oraclejdk7
          env: FOO=bar BAR=foo

notifications:
    email:
        recipients:
            - cwczip742@naver.com
        on_success: always
        on_failure: always

# blacklist
branches:
    except:
        - experimental
        - try-yourself

# whitelist
branches:
    only:
        - master
