before_install:
    - sudo apt-get install -qq tree

language: java
jdk:
  - oraclejdk7
after_success:
  - tree

language: python
python:
    - "2.7"

install:
    - "pip install -r requirements.txt"

script: ./scripts/run-tests.sh

addons:
  hosts:
    - travis.example
